server:
  port: 8080

spring:
  application:
    name:
      User
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aditya@321
    url: jdbc:mysql://localhost:3306/vinculum?
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop