version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  rabbitmq:
    image: rabbitmq-plugin
    ports:
      - "15672:15672"
      - "61673:61673"
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411