version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - postgres
  rabbitmq:
    image: rabbitmq-plugin
    ports:
      - "15672:15672"
      - "61673:61673"
      - "5672:5672"
    networks:
      - spring
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    networks:
      - spring
  eureka-server:
    image: bhatanagar10/eureka-discovery-server
    ports:
      - "8010:8010"
    depends_on:
      - zipkin-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
  api-gateway:
    image: bhatanagar10/api-gateway
    ports:
      - "8030:8030"
    depends_on:
      - eureka-server
      - zipkin-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge